# Site settings
title: Compose
email: mdb@samskivert.com
baseurl: "/compose"
url: "http://samskivert.github.io/compose"
repository: samskivert/compose
twitter_username: samskivert
github_username: samskivert
show_downloads: false

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
